### ISSUE TITLE
Documentation not existent

### ISSUE THREAD

**Issue by XilefTech** [XilefTech/CharlieOSX#1] opened 2020-01-24 14:07 UTC
I'm aware that there is almost no documentation in and around the code except for the config file.

At the moment I'm concentrating on getting basic functionality for all robot types with the number codes working.
When I'm finished with that I'll do the documentation for the hole Project.

I hope you can understand that.

**Comment by TheGreyDiamond** [comment] 2020-08-12 19:30
Will this ever happen?

**Comment by XilefTech** [comment] 2020-08-12 19:58
Sure
At the moment I'm focusing on bringing the basic functionality to CharlieOSX. I think I got most done by the end of this week and then, I'll probably do at least some of the documentation

**Comment by TheGreyDiamond** [comment] 2020-08-12 19:58
Duplicate of #10

**Comment by XilefTech** [comment] 2020-08-29 17:34
@TheGreyDiamond I now created a wiki here in this repo. It should contain most information about CharlieOSX, but I am still working on it. If I totally missed some point in there, let me know (except the method usage in the class documentationm I am aware of that one and will add it soon)

Also the Documentation in-code with comments etc. is following soon<sup>TM</sup>

**Closed** 2020-09-05 23:04 UTC
Labels: documentation
